### ISSUE TITLE
Infinite paging occurs when a document contains an ultra wide picture

### ISSUE THREAD

**Issue by lovebigbird** [pagedjs/pagedjs#1]
I set up the A4 page, but if my page contains a wider picture, it will result in infinite paging

**Comment by julientaq** [comment]
@lovebigbird thanks for the issue. I’m gonna duplicate it on our gitlab dev instance.

To avoid this, you can already put this in your css

`img { max-width: 100% }`

you should be saved through here.

**Comment by julientaq** [comment]
Your issue will be discussed here

→ https://gitlab.pagedmedia.org/tools/pagedjs/issues/158

**Comment by julientaq** [comment]
Closing this as a new version of paged.js (0.41) handles the infinite loop. (it stops the rendering where the book has a problem).
