### ISSUE TITLE
Running elements not being copied to margin

### ISSUE THREAD

**Issue by henriquecm** [pagedjs/pagedjs#118]
I followed the example on https://pagedjs.org/documentation/7-generated-content-in-margin-boxes/
I've even tried copying a simpler example, page counter, but not even that worked.

I am missing something, or something else in my code is interfering.

https://codepen.io/henriquecm8/pen/oNMpoEB

**Comment by julientaq** [comment]
hi there.
so yes, you’re not sending any css to pagedjs. 

if you remove the `pagedjs-data-ignore` attribute from your style, the css is used.

your other solution is to send the css as a string instead of having it in a style element.

**Comment by henriquecm** [comment]
Thanks, that worked, I'll have to revise this css later than. But for now it's right how I wanted.
