### ISSUE TITLE
Is it possible to set the size of the margin boxes?

### ISSUE THREAD

**Issue by Eric24** [pagedjs/pagedjs#13]
Currently, one dimension is set by the page margin and the other dimension is set "automagically" based on whether there is or isn't content in a particular margin box. But what if I wanted an asymmetrical margin box, say `@bottom-left` that was 75% the width of the page area and `@bottom-right` then taking up the remaining 25%?

**Comment by julientaq** [comment]
hi @Eric24 thanks for your issue.
If you check the pagedmedia specs, the automagically are what the browsers are supposed to do :) You can set up the size of the margin-boxes using the `width` property.  
Did you try that already?

some documentation to help https://www.pagedjs.org/documentation/07-generated-content-in-margin-boxes/#define-width-and-height-of-margin-boxes

Please tell us if you manage to make it work as you’d want or if we need to dig together :)

**Comment by julientaq** [comment]
Hi @Eric24, did that comment help you?

**Comment by Eric24** [comment]
Yes. That's exactly what I was looking for. Thanks!
