### ISSUE TITLE
HTML is hidden as soona s I link to a style.css

### ISSUE THREAD

**Issue by WunschK** [pagedjs/pagedjs#131]
Hi there, 

I have played around with pagedJS before and wanted to give it another try :-) 

```
<head>
    
    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/pagedjs/dist/paged.polyfill.js"></script>
   <link rel="stylesheet" href="test.css" media="screen"/>
<!-- <link rel="stylsheet" href="print.css" media="print"/>-->
    <title>Document</title>

</head>
```
As soon as I add the print stylesheet stylesheet, I get  only a white screen. The content is hidden in the following snippet: 

```
<body><template data-ref="pagedjs-content">
    <h1>Test</h1>
    <div id="content">
  ... </div>
</template>
</body>
```

with only the test.css (media="screen"), I get the same at first, but then additionally `div.paged_js_pages` below with the actual content.

I will have several css-files later on, that are imported so that the cascading rules can overwrite pre-defined rules. However, whenever I activate (or deactivate) the polyfill, my website changes. 

any hints and better examples for starting with pagedJS? :-) 

edit: 

whenever I have the pagedJS polyfill and a css-file on my exist-instance (I cannot get anything shown, at all) but that's a story for another day.

**Comment by julientaq** [comment]
nice to read you found a way out :)
