### ISSUE TITLE
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': 'link[rel='stylesheet']:not([data-pagedjs-ignore], [media~='screen'])”

### ISSUE THREAD

**Issue by Bubblex** [pagedjs/pagedjs#132]
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': 'link[rel='stylesheet']:not([data-pagedjs-ignore], [media~='screen'])'is not a valid selector.

**Comment by Bubblex** [comment]
problem solved

`querySelectorAll(
          "style:not([data-pagedjs-inserted-styles]):not([data-pagedjs-ignore]):not([media~='screen'])"
        )`

**Comment by Bubblex** [comment]
problem solved

`querySelectorAll(
          "link[rel='stylesheet']:not([data-pagedjs-ignore]):not([media~='screen'])"
        )`

**Comment by julientaq** [comment]
hi there.

i don’t understand your problem. neither your solution :D 

would you mind gaving a little bit more info?

**Comment by Bubblex** [comment]
This error will be reported when the browser of the lower version (chrome73) is running, and it is later found that the :not selector does not take effect in the lower version

**Comment by julientaq** [comment]
[](url)
