### ISSUE TITLE
Table header (thead) doesn't repeat on next pages

### ISSUE THREAD

**Issue by Simply1993** [pagedjs/pagedjs#139]
Repeating thead is default behavior for long table.

<details><summary>First screenshot - Correct behavior</summary>
<img width="620" alt="Correct" src="https://user-images.githubusercontent.com/28846237/236245050-a11d84e8-25e7-403d-b674-958a89244178.png">
</details>

But if I used paged.js, then this behavior breaks and I missed row "033".
Head-111111 is missing in 2nd page, have only next Head-222222, but in incorrect place, it must be after row "050".

<details><summary>Second screenshot - Incorrect behavior</summary>
<img width="356" alt="Incorrect" src="https://user-images.githubusercontent.com/28846237/236245087-97181464-76bb-4bac-90bd-22f20c40d130.png">
</details>

I expect behavior like on the first screenshot.

I use paged.polyfill.js

**Comment by Simply1993** [comment]
If anyone need it, I made handler
It work for me

```
class TableHeadClone extends Paged.Handler {
            constructor(chunker, polisher, caller) {
                super(chunker, polisher, caller);
                this.styleSheet = polisher.styleSheet;
                this.theadElementsByTbodyKey = {};
            }

            afterParsed(parsed) {
                parsed.firstElementChild.querySelectorAll('thead').forEach((elThead, idx) => {
                    const nextElement = elThead.nextElementSibling;

                    if (nextElement.tagName === 'TBODY') {
                        const ref = nextElement.dataset.ref;

                        this.theadElementsByTbodyKey[ref] = elThead;
                    }
                });
            }

            afterPageLayout(pageElement, page, breakToken) {
                Object.entries(this.theadElementsByTbodyKey).forEach(([ref, theadElement]) => {
                    pageElement.querySelectorAll(`tbody[data-ref="${ref}"]`).forEach((elTbody) => {
                        if (!elTbody.previousElementSibling || elTbody.previousElementSibling.tagName !== 'THEAD') {
                            if (breakToken) {
                                breakToken.node = breakToken.node.previousElementSibling;
                            }
                            const clone = theadElement.cloneNode(true);
                            elTbody.parentNode.insertAdjacentElement("afterbegin", clone)
                        }
                    });
                });
            }
        }
```

**Comment by mersa2024** [comment]
This is not working after the second page.

**Comment by julientaq** [comment]
@mersa2024 would you mind sharing html and css? 
Because it’s really dependant of what you’re tryting to layout.

also, would you mind sharing https://unpkg.com/browse/pagedjs@0.5.0-beta.1/ ? thank you
