### ISSUE TITLE
Footnote 21 from the the footnote spec falls into the next page

### ISSUE THREAD

**Issue by eduarevalo** [pagedjs/pagedjs#143]
As appears in the screen capture, footnote 21 falls into the next page.
This is taken from the file `specs/notes/footnotes/footnotes.html`

I assume this is a bug 
![footnote-error](https://github.com/pagedjs/pagedjs/assets/20518796/9cacd308-cbff-4ecf-ae08-b02ef001f9ad)

**Comment by julientaq** [comment]
hi there.

it is not, it’s how footnotes-policy work: https://www.w3.org/TR/css-gcpm-3/#footnote-policy

you can check the other option and see if you prefer what you get there.

**Comment by eduarevalo** [comment]
@julientaq Thanks for your support and quick reply

**Comment by julientaq** [comment]
thanks for the reminder that i need to write about footnotes in the docs :D
