### ISSUE TITLE
Trouble keeping elements together across page break

### ISSUE THREAD

**Issue by nicgordon** [pagedjs/pagedjs#146]
Hello, I am having some difficulty keeping some elements "stuck" together across a page break. I have 3 elements in this order: 
- `h4` with `break-after: avoid;`
- `p` with `break-after: avoid; break-before: avoid;`
- `table` with `break-before: avoid;`

I would like to keep them all together, and if they overflow a page then they all move to the next page together, but it is having strange results. It seems that the `p` and the `table` will happily stick together but they'll always abandon the `h4` on the previous page for some reason.

I have also wrapped them in a container `div` element with `break-inside: avoid;` on it (and I have tried `break-inside: avoid-column;` as well) to no avail.

Here are some example images of what I am experiencing:

![image](https://github.com/pagedjs/pagedjs/assets/2223986/f87a296a-b45e-4b17-b487-76e7e0ec0266)
![image](https://github.com/pagedjs/pagedjs/assets/2223986/a6c48788-273e-4d86-9636-9762f5008a70)

Does anyone have any suggestions for me? Thank you

**Comment by nicgordon** [comment]
I found a workaround by looking through the other issues. I noticed that it was suggested elsewhere to apply `break-inside: avoid;` to a `tr`. So I have replaced my container `div` with a whole `table > tbody > tr > td` structure and then applied that style to the `tr` and it seems to be working and keeping them together. Not the most ideal structure, but it works

**Comment by julientaq** [comment]
hi there.

so yeah you don’t wanna make some weird html to fix bugs, i agree.

if you want to keep one element together, adding `break-inside: avoid` to the parent should do the trick.

that said, it’s a browser thing. If chrome decide that the table will not have enough room on the page, it will move it to the next one, regardless of the break avoid property.

I also did this very small and hacky hook for when you have two break-avoid element taht follow each other and that the browser dont do anything about: https://pagedjs.org/plugins/temporary-fix-for-break-after-avoid/

**Comment by nicgordon** [comment]
Thank you for the response, I suppose this can be closed then given that there are a couple of workarounds here for others to use should they come across this issue in their own work.
