### ISSUE TITLE
Why does paged.js exist on both github and gitlab?

### ISSUE THREAD

**Issue by Eric24** [pagedjs/pagedjs#15]
Which is considered the "main" project, for releases as well as issues?

**Comment by julientaq** [comment]
Pagedjs on github is supposedly simpler to access for other developers while our self hosted gitlab instance is our development repo. You’re welcome to open issue on both :)

Full disclosure: we’re still discussing about what we should do in the team: we want to be accessible to the broader community so we have a github account, but the merge request and development is on gitlab. 

For now, the burden of having two places for issues and bugs haven’t been that complex, so it’s not really hard to maintain for us (for now). I think that we’ll ask ourselve the question when someone will try a pull request from github.

Meantime, the repo are cloned. So you’ll have the same files in both envrironment :)

**Comment by Eric24** [comment]
OK. Thanks for the quick response.
