### ISSUE TITLE
How do I debug this target-text() issue?

### ISSUE THREAD

**Issue by Jeff-Tian** [pagedjs/pagedjs#151]
I referenced this https://pagedjs.org/documentation/-cross-references/ doc and tried to add a cross-reference but failed.

The content didn't show up, as the following image shows:

<img width="1919" alt="image" src="https://github.com/pagedjs/pagedjs/assets/3367820/2e2aa535-b03d-4655-8af1-2a9567b4c23e">

My CSS is as following:

<img width="756" alt="image" src="https://github.com/pagedjs/pagedjs/assets/3367820/33e55ff8-41ff-4156-80f2-96bfa2c27328">

I can see my `target-text(attr(href url))` part was replaced to `var(--pagedjs-7a859253-16a6-4fe6-a4ba-0e562277ec9b)`.

Was it because `--pagedjs-7a859253-16a6-4fe6-a4ba-0e562277ec9b` point to a non exist element? How could I debug it?

Reproduce URL: https://identity.jefftian.dev/main.html

**Comment by Jeff-Tian** [comment]
Fixed by adding a `#`, misled by this part:
<img width="1298" alt="image" src="https://github.com/pagedjs/pagedjs/assets/3367820/f1ef8998-c680-4016-b12d-41aee0ad044a">

**Comment by julientaq** [comment]
ho you’re so right! 

thank you. i’m gonning to fix that right now.
