### ISSUE TITLE
Break-before: column doesn't work unless it is added inline in html

### ISSUE THREAD

**Issue by ihor-z-i** [pagedjs/pagedjs#16]
Given that the column layout is used
```
.columns {
  columns: 4;
}
```
When the rule is declared in CSS such as following it doesn't work because pagedjs overrides it.
```
.col-break-before{
  break-before: column;
}
```
The expected behavior is that it should work without inline styles. If that is not possible, it needs to be documented somewhere as a limitation.

There is a workaround for that: adding inline style declaration, such as:

```
    <h1 style="break-before:column;">
      Column should break before
    </h1>
```

Here is an example:
https://jsfiddle.net/bmjduw6q/18/

**Comment by julientaq** [comment]
Ha thanks!
we’ll look into it.

**Comment by julientaq** [comment]
you can follow this here: https://gitlab.pagedmedia.org/tools/pagedjs/issues/196
