### ISSUE TITLE
Table is overlapping with the page numbers section, when page is ending with a table.

### ISSUE THREAD

**Issue by lohithdhanakonda** [pagedjs/pagedjs#17]
When a page is ending with a table, I am having issues. The table is overlapping with the page number section, sometimes even truncating the table abruptly, though I am using
`table, tr {
    break-inside: avoid;
}`
in my stylesheet. 
Actually it has to avoid page breaking inside the Table. While I am doing it without pagedjs it is fine, i.e., with plain HTML, CSS the page is breaking correctly since I mentioned `break-inside: avoid;` for `tr` if the table is at the end of the page, it breaks the page inside table without any overlapping, continues the remaining table in the next page.
Is there any way that I can get?
I am posting the screenshots here, let me know if you need anything else in order to help me out.

![image](https://user-images.githubusercontent.com/23074579/80897846-b5facc80-8d1a-11ea-8177-5d873f1eeea4.png)
![image](https://user-images.githubusercontent.com/23074579/80898167-f576e800-8d1d-11ea-8b1c-7a27553b6bbd.png)

**Comment by julientaq** [comment]
closing as it’s discussed here: https://gitlab.pagedmedia.org/tools/pagedjs/issues/209
