### ISSUE TITLE
Table starts on next page if an element is in front of it

### ISSUE THREAD

**Issue by gyoengyoesi** [pagedjs/pagedjs#175]
Hi,

I use paged.js to create documents with a correct print preview.
@julientaq first of all, thank you for the project and the great work. It has really helped me a lot.
I currently have the following problem with tables.

As soon as I place an element in front of a table, the table does not start immediately after the element, but on the next page.

![image](https://github.com/pagedjs/pagedjs/assets/65939323/99fa8e16-e39e-45ea-878a-2c13065c6655)

As soon as the table is the first element, the table also starts at the beginning of the first page.

![image](https://github.com/pagedjs/pagedjs/assets/65939323/9695675a-8c0c-42e8-8f87-18eb9268e270)

Tested with version 0.4.3. and 0.5beta

[sample.html.zip](https://github.com/pagedjs/pagedjs/files/13522511/sample.html.zip)

Is there any idea why this could be?

Thanks

**Comment by julientaq** [comment]
oh are you using firefox?

**Comment by gyoengyoesi** [comment]
Oh yes, I do that.
I just saw that it actually works in Chrome. 
Is there any fix for Firefox?

Thanks for the hint.

**Comment by julientaq** [comment]
ha dang.

I wish we could have a simple fix for firefox but we don’t yet.

Firefox hasn’t implemented a lot of the pagebreak that blink has yet. (i hope they’ll get to that at some point).

To support firefox on those, we’d need to reimplement the whole page break system, and i’m not sure that @fchasen would agree with this, as it may be under work in Firefox.

**Comment by julientaq** [comment]
your only solution is to have a chromium on your computer to generate the pdf or use the pagedjs-cli. (i know it’s a shame, i have this exact setup on my computer).

**Comment by gyoengyoesi** [comment]
Thank you very much.
Then that's our solution for now.

**Comment by julientaq** [comment]
(thanks for the kind words :D)
