### ISSUE TITLE
Not listening to @media screen

### ISSUE THREAD

**Issue by map7** [pagedjs/pagedjs#177]
I've got the following report

```
<html>
  <head>
    <script src="https://unpkg.com/pagedjs/dist/paged.polyfill.js"></script>

    <style type="text/css">
     @media screen {
       .nav {
         width: 100%;
         height: 40px;
         background: black;
         color: white;
         font-weight: bold;
         margin-bottom: 20px;
       }
     }
     
     @media print {
       .nav {display: none;}
      }
    </style>
  </head>
  
  <body>
    <div class="nav">
       Navigation
    </div>

    <p class="footer"><i>Testing</i> Footer with italics </p>

     <div id="main">my report</div>
  </body>
</html>
```

When I view this on the screen I cannot see the nav div. It's like pagedjs is only listening to '@media print' even when I'm displaying on the screen.

**Comment by julientaq** [comment]
Hi there.

yes, that’s expected. Pagedjs will not look at the screen css to avoid css mix and matching, it’s explained here: 

https://pagedjs.org/posts/paged-break-the-long-overdue-update/

we did put a backdoor in there. you can check this example to see how to add the `pagedjs-ignore` keyword in the css file.

https://gitlab.coko.foundation/pagedjs/interface-polyfill/-/raw/master/interface.css

**Comment by map7** [comment]
Thanks @julientaq, that's what I was looking for. Just enough to put a little menu on the screen when previewing my reports.
