### ISSUE TITLE
Using pagedjs with css grid distorts the contents

### ISSUE THREAD

**Issue by zahrafali** [pagedjs/pagedjs#18]
<img width="1440" alt="Screenshot 2020-05-15 at 1 48 19 AM" src="https://user-images.githubusercontent.com/25129766/81981655-39d38380-964e-11ea-835c-18fbfff5e4d5.png">

```
import React from "react";
import "./App.css";
import styled from "styled-components";
const Grid = styled.div'
  display: grid;
  width: 8in;
  grid-template-columns: 1fr 1fr;
';

const Center = styled.div'
  display: grid;
  place-items: center;
  @media print {
    page-break-after: always;
  }
';
const Col1 = styled.div'
  grid-column: 1 / span 1;
';
const Col2 = styled.div'
  grid-column: 2 / span 1;
';
function App() {
  return (
    <div>
      <Center>
        <Grid>
          <Col1>
            1Lorem ipsum door ...
          </Col1>
          <Col2>
            Lorem ipsum dolor ...
          </Col2>
        </Grid>
      </Center>
    </div>
  );
}

export default App;
```

when I use ```import {} from "pagedjs/dist/paged.polyfill";```

The content distorts like - 
<img width="1440" alt="Screenshot 2020-05-15 at 1 51 28 AM" src="https://user-images.githubusercontent.com/25129766/81981926-9df64780-964e-11ea-9ab9-602642bb8629.png">

**Comment by zahrafali** [comment]
https://codesandbox.io/s/confident-raman-gukp4?file=/src/App.js

**Comment by julientaq** [comment]
Hey there!

i was going to answer and then i saw you opened the issue in the gitlab.
Thanks!

i’m closing this issue, let’s discuss on https://gitlab.pagedmedia.org/tools/pagedjs/issues/206
