### ISSUE TITLE
I created the iframe tag by js, the home header disappeared

### ISSUE THREAD

**Issue by EnochGao** [pagedjs/pagedjs#185]
I used the latest version and found that when I created the iframe tag, the home header disappeared [demo](https://github.com/EnochGao/html)

![image](https://github.com/pagedjs/pagedjs/assets/41459067/5b6364fc-2089-4daf-afb9-1b3bffe238b4)

**Comment by EnochGao** [comment]
@NigelCunningham

**Comment by NigelCunningham** [comment]
Thanks!

**Comment by NigelCunningham** [comment]
It's working for me, sorry. What I did:

Starting in the root of my copy of the pagedJS repository:

```
git checkout main
git pull
npm run build
git clone https://github.com/EnochGao/html.git enochgao
cd enochgao
rm v2paged.polyfill.min.js
ln -s ../dist/paged.polyfill.min.js v2paged.polyfill.min.js
npx live-server
```

**Comment by EnochGao** [comment]
> It's working for me, sorry. What I did:
> 
> Starting in the root of my copy of the pagedJS repository:
> 
> ```
> git checkout main
> git pull
> npm run build
> git clone https://github.com/EnochGao/html.git enochgao
> cd enochgao
> rm v2paged.polyfill.min.js
> ln -s ../dist/paged.polyfill.min.js v2paged.polyfill.min.js
> npx live-server
> ```

[i created a iframe branch with demo ](https://github.com/EnochGao/pagedjs/tree/iframe)

https://github.com/pagedjs/pagedjs/assets/41459067/f7609aaf-782c-4dd8-896e-616ea813e7d5

**Comment by NigelCunningham** [comment]
Have you checked for any errors in the browser's dev console?

**Comment by NigelCunningham** [comment]
The issue is related to something called running selectors, which I've not previously seen. The first header is there but is having display:none applied to it. I've got to go out now; I'll do some more investigation later.

**Comment by NigelCunningham** [comment]
I actually think this has nothing to do with the pagination changes - it looks to me like the iframes are irrelevant (I can reproduce the issue without them), and the Running Headers code has multiple issues - it looks like it's failing to move the content into the destination zones (or whatever they're called), making the first one hidden when it shouldn't and processing things more than once. I can have a go at fixing those things, but not today :\

**Comment by EnochGao** [comment]
> I actually think this has nothing to do with the pagination changes - it looks to me like the iframes are irrelevant (I can reproduce the issue without them), and the Running Headers code has multiple issues - it looks like it's failing to move the content into the destination zones (or whatever they're called), making the first one hidden when it shouldn't and processing things more than once. I can have a go at fixing those things, but not today :\

thanks, i tried the previous version and it worked fine. not sure what caused it

**Comment by NigelCunningham** [comment]
Well then, I must have broken it. That removes all excuse for me to be lazy!

I'll look at it some more.

Nigel

**Comment by EnochGao** [comment]
> hey
> 
> i’ve got everything working as intended in chromium.
> 
> ![Screenshot 2024-03-18 at 10 57 16](https://private-user-images.githubusercontent.com/2174473/313629701-10a96e73-ac5f-476b-af3a-41f3b081a4a6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTg5NDIsIm5iZiI6MTcxMDc1ODY0MiwicGF0aCI6Ii8yMTc0NDczLzMxMzYyOTcwMS0xMGE5NmU3My1hYzVmLTQ3NmItYWYzYS00MWYzYjA4MWE0YTYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMTA0NDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODZiODRkZTliMzJkMWRiZDhlM2UxOTZmYTllNjNjNmZjYzI1MzM0MDJiNWQwYWU4N2U1YTI2ZDI1MWE4Yjg3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KeajgwilHaMExdLVPhPaTvN7UanPmg3OwbuXHxKi3-Q)
> 
> (added some interface.css to test).
> 
> Is that what you’re trying to achieve?
> 
> I’m trying to understand why you have the problem. Which os? which version of the os?

great! I hope that's it.Is this implemented in an iframe？[issue demo ](https://github.com/EnochGao/pagedjs/tree/iframe) I used the latest version of the edge browser. What puzzles me is that it is normal for it not to be placed in an iframe.

**Comment by julientaq** [comment]
ok that’s different. There is something else going on. The two issues are mixing.

**Comment by EnochGao** [comment]
> ok got it. 好的，知道了。
> 
> so what happens is that the way you set up the content, pagedjs adds the page before the content is already found.所以，你设置内容的方式，pagedjs 在内容已经找到之前添加页面。
> 
> so it creates a page widht the @page model and then put content in. At the moment it creates the page, it has not yet encountered the content that should be on the top of the page yet, thus the header for the page is empty.所以它创建了一个带有模型的页面，然后把内容放进去。在创建页面的那一刻，它还没有遇到应该在页面顶部的内容，因此页面的标题是空的。
> 
> But if we put the content first, then we can see it appears on the top of the page.但是如果我们把内容放在前面，那么我们可以看到它出现在页面的顶部。
> 
> Which is the normal behavior.这是正常的行为。
> 
> This works fine (i put the header before the section)这个工作正常(我把标题放在章节之前)
> 
> ```
> 
> 		<div id="printEL">
> 			<header class="common-header mate-pro-header">
> 					<img
> 						src="https://consumer.huawei.com/content/dam/huawei-cbg-site/cn/mkt/pdp/phones/mate60-pro/img/list-img/green.png"
> 					/>
> 					<span class="common-title">HUAWEI Mate 60 Pro评价表（第一份）</span>
> 				</header>
> 
> 
> 			<section class="mate-pro">
> 							<footer class="common-footer mate-pro-footer">
> 					页脚 mate 60 pro（第一份）
> 				</footer>
> ```
> 
> We need to keep that behavior, because maybe you don’t want to see the element BEFORE it appears in the content. But we could definitely think of some css to have way to author this in the futur.

wow! That's great! I see. I put them in the section in the previous version, but I didn't think it was for this reason. Thank you very much for your help🥳

**Comment by EnochGao** [comment]
It worked. Thank you very much for your help

**Comment by NigelCunningham** [comment]
I think there's still an issue to be dealt with here - the "headers" aren't put in the header parts of the page but at the top of the content, unless I'm mistaken?

**Comment by julientaq** [comment]
the header are set correctly once placed at their right position in the html: before they need to appear on the page.

Thus the issue can be closed.
