### ISSUE TITLE
A large number of table pages are abnormal in version 0.50-beta

### ISSUE THREAD

**Issue by EnochGao** [pagedjs/pagedjs#191]
If the page contains table, let a few tds fill a lot of data to generate paging, the first page and the second page will lose td.

[table.txt](https://github.com/pagedjs/pagedjs/files/14646806/table.txt)

![image](https://github.com/pagedjs/pagedjs/assets/41459067/ef7519af-17e1-4a47-992f-0ffdd6e3a2b9)

**Comment by julientaq** [comment]
Hey there.

would you mind explaining a bit more what’s happening and put a .txt file with the html, css and js you use? It’s easier to test than having to clone another repo and navigate in different version of pagedjs?

i believe that what you have here is the result of some css rules, but i d like to check the html/css to be sujre.

**Comment by EnochGao** [comment]
> Hey there.
> 
> would you mind explaining a bit more what’s happening and put a .txt file with the html, css and js you use? It’s easier to test than having to clone another repo and navigate in different version of pagedjs?
> 
> i believe that what you have here is the result of some css rules, but i d like to check the html/css to be sure.

All right, copy that.

**Comment by julientaq** [comment]
got it. Thank you!

**Comment by julientaq** [comment]
ok so i guess that most of the work from @NigelCunningham was to support this. 

i havent got the time to get through that code yet, and i’m not sure i got all the changes in my brain yet. 
@NigelCunningham and @fchasen do you wanna have a look at it?

**Comment by NigelCunningham** [comment]
Ok, I know what's going wrong here - my thinking was wrong in setting siblingRangeEnd within findOverflow. It's taking the reminder of the row but should just take the reminder of the td, then check for overflow in the other tds too.

**Comment by NigelCunningham** [comment]
https://github.com/pagedjs/pagedjs/pull/196

**Comment by EnochGao** [comment]
> #196
There are still some problems. The second row is missing
![image](https://github.com/pagedjs/pagedjs/assets/41459067/5f9c9249-460e-4b47-b697-85b57e5a7cf1)

**Comment by NigelCunningham** [comment]
Please retest with the latest pushes for #196. Thanks!

**Comment by EnochGao** [comment]
No problems found, thank you for your efforts
