### ISSUE TITLE
Installation issue with pagedjs-cli

### ISSUE THREAD

**Issue by zopyx** [pagedjs/pagedjs#2]
I followed the installation instructions on https://www.pagedjs.org/documentation/99-command-line-interface/ and getting this error both under MacOSX and Linux:

```
pagedjs-cli lessons/lesson-basic/index.html
◷ Loading: lessons/lesson-basic/index.html(node:12160) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/ajung/.nvm/versions/node/v12.13.0/lib/node_modules/pagedjs/dist/paged.polyfill.js'
  -- ASYNC --
    at Frame.<anonymous> (/home/ajung/.nvm/versions/node/v12.13.0/lib/node_modules/pagedjs-cli/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.addScriptTag (/home/ajung/.nvm/versions/node/v12.13.0/lib/node_modules/pagedjs-cli/node_modules/puppeteer/lib/Page.js:421:29)
    at Page.<anonymous> (/home/ajung/.nvm/versions/node/v12.13.0/lib/node_modules/pagedjs-cli/node_modules/puppeteer/lib/helper.js:112:23)
    at Printer.render (/home/ajung/.nvm/versions/node/v12.13.0/lib/node_modules/pagedjs-cli/src/printer.js:98:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Printer.pdf (/home/ajung/.nvm/versions/node/v12.13.0/lib/node_modules/pagedjs-cli/src/printer.js:226:16)
    at async /home/ajung/.nvm/versions/node/v12.13.0/lib/node_modules/pagedjs-cli/bin/paged:137:14
(node:12160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by julientaq** [comment]
hey @zopyx thanks

would you please try to install pagedjs globally: 
`npm install -g pagedjs` and try the command again?

@fchasen i believe that there is a dependency error here.

**Comment by julientaq** [comment]
This is now fixed.
i just installed `Pagedjs-cli` globally and it doesnt have the problem anymore.

I close the issue, feel free to reopen it if you still get the problem.

**Comment by zopyx** [comment]
Installing things globally is neither a reasonable solution nor a recommended way. As with various other languages, we work with local environment with Python or NodeJS. And things are supposed to work both ways. Nobody wants to mess up a global installation. This is bad practice.

**Comment by julientaq** [comment]
Thanks for your input. I also prefer local over global installation. But it comes with complexities and specificities that would make support more complex. We’ll get there eventually, but for now, the simplest way is to set up `Pagedjs-CLI` globally and start playing with it. 

If you really want to work in a local environment, you could install `Pagedjs-cli` in the folder of your choice and set up the `path` in your shell configuration to run from a custom environment.  

For example, you could `npm install pagedjs-cli` in the folder you want to use the CLI and `node node_modules/pagedjs-cli/bin/paged file.html` to run it. But beware, as it will need to reinstall the dependencies everytime you’ll need it in a new folder.

And if you want to go deeper, you can have a look at how the folks at https://www.coko.foundation are building Editoria, using a docker environment to produce the pdf: [https://gitlab.coko.foundation/editoria/editoria/tree/master/packages/job-pdf](). 

It really depends on your level and technical knowledge.

**Comment by esetera** [comment]
hi @zopyx 

By way of intros, I'm Adam - the founder of Pagedjs and part of the team. 

So first, nice to see you here. We are fans of Print CSS Rocks and it means a lot for us to see you here and participating in the Pagedjs discussion.

Second, I would ask you to please be less abrasive in your communications. We don't welcome sharpness. If you would like to continue these discussions in a friendly tone we would love that and welcome you to our humlbe and happy community.

Adam

**Comment by zopyx** [comment]
Sorry but there is no sharpness. I am now trying to get a working installation for the 3rd or 4th time. And please take such bug reports seriously. A global installation is just not the usual way to installing things. And the "getting started" experience at the moment is not great.

**Comment by esetera** [comment]
I'm afraid we are at a disagreement @zopyx - this comment now, and the previous comment are not friendly. I'd like to help you understand what we expect from these communications so that we can continue to collaborate with you, otherwise we are not interested.  If you like I'd be happy to jump on a call and chat.

**Comment by zopyx** [comment]
As said: a global installation of tools is usually undesired - in particular when you have to deal with different versions of tools. That's why you want support for virtualenv  (python) or related solutions for NodeJS. In particular when you want to test software having different requirements and dependencies. Putting all and everything into a global installation is bad practice...perhaps acceptable for now but unlikely for the future or running things in production.

**Comment by zopyx** [comment]
And the problem remains the same with global installation:

```
pagedjs-cli
internal/validators.js:112
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.resolve (path.js:981:7)
    at Object.<anonymous> (/home/ajung/.nvm/versions/node/v12.13.0/lib/node_modules/pagedjs-cli/bin/paged:55:23)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'ERR_INVALID_ARG_TYPE'
}
ajung@dev2 ~ $ which pagedjs-cli
/home/ajung/.nvm/versions/node/v12.13.0/bin/pagedjs-cli
```

**Comment by esetera** [comment]
Thank you @zopyx for softening the tone. I very much appreciate it. Your advice and insights on how to improve pagedjs are deeply valued. I'll ask @julientaq to bring this item up re global installs and report back on how we can address it.

**Comment by julientaq** [comment]
> Putting all and everything into a global installation is bad practice...perhaps acceptable for now but unlikely for the future or running things in production.

exactly what i said in my previous longer answer.

@zopyx as i said in https://github.com/pagedjs/pagedjs/issues/3 the only way i got to recreate your issue was to not give any file name.
Running `pagedjs-cli` will set an issue. We’ll update the CLI to have a more understandable error messages. 
Could you tell me what happens when you run `pagedjs-cli name-of-the-file.html` in the terminal?

**Comment by zopyx** [comment]
Using a global installation throws a different error that I reported already earlier:

```
 pagedjs-cli foo.html
◴ Loading: foo.html(node:14418) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/ajung/.nvm/versions/node/v12.13.0/lib/node_modules/pagedjs/dist/paged.polyfill.js'
  -- ASYNC --
    at Frame.<anonymous> (/home/ajung/.nvm/versions/node/v12.13.0/lib/node_modules/pagedjs-cli/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.addScriptTag (/home/ajung/.nvm/versions/node/v12.13.0/lib/node_modules/pagedjs-cli/node_modules/puppeteer/lib/Page.js:421:29)
    at Page.<anonymous> (/home/ajung/.nvm/versions/node/v12.13.0/lib/node_modules/pagedjs-cli/node_modules/puppeteer/lib/helper.js:112:23)
    at Printer.render (/home/ajung/.nvm/versions/node/v12.13.0/lib/node_modules/pagedjs-cli/src/printer.js:98:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Printer.pdf (/home/ajung/.nvm/versions/node/v12.13.0/lib/node_modules/pagedjs-cli/src/printer.js:226:16)
    at async /home/ajung/.nvm/versions/node/v12.13.0/lib/node_modules/pagedjs-cli/bin/paged:137:14
(node:14418) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14418) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 ```

**Comment by zopyx** [comment]
And the same result on Mac:

```
pagedjs-cli foo.html
◷ Loading: foo.html(node:41894) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/pagedjs/dist/paged.polyfill.js'
  -- ASYNC --
    at Frame.<anonymous> (/usr/local/lib/node_modules/pagedjs-cli/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.addScriptTag (/usr/local/lib/node_modules/pagedjs-cli/node_modules/puppeteer/lib/Page.js:421:29)
    at Page.<anonymous> (/usr/local/lib/node_modules/pagedjs-cli/node_modules/puppeteer/lib/helper.js:112:23)
    at Printer.render (/usr/local/lib/node_modules/pagedjs-cli/src/printer.js:98:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Printer.pdf (/usr/local/lib/node_modules/pagedjs-cli/src/printer.js:226:16)
    at async /usr/local/lib/node_modules/pagedjs-cli/bin/paged:137:14
(node:41894) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:41894) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by julientaq** [comment]
@zopyx thanks for the update.

I’m gonna update the docs until @fchasen update the dependencies tree of paged.js cli.

you need to install pagedjs and pagedjs-CLI as the first is a dependency of the latter. I thought this was fixed in the last update, but apparently it’s not yet. @fchasen could you check.

Meanwhile, @zopyx could you try to run `npm install -g pagedjs pagedjs-cli` and try again?

Please tell us how it goes.

**Comment by zopyx** [comment]
``` npm install -g pagedjs pagedjs-cli ```

solves the problem for the global installation.

**Comment by zopyx** [comment]
And again: their was no offense in my bug report. But it's all about the "getting started" experience for someone trying out your project.

**Comment by julientaq** [comment]
Thanks for letting us know!

**Comment by julientaq** [comment]
@zopyx no problem at all, we appreciate the input.

**Comment by zopyx** [comment]
btw. I am preparing print-css.rocks for pagedjs

**Comment by esetera** [comment]
awesome :)

**Comment by Loots-it** [comment]
It seemed like I had the same issue, although this:

`
npm install -g pagedjs pagedjs-cli
`

also solved my problem. The local install didn't work.

**Comment by Einenlum** [comment]
Same for me. Installing it with `pagedjs` fixed the issue.

The documentation page uses a different order: https://pagedjs.org/documentation/2-getting-started-with-paged.js/#command-line-version

It should be updated. A small note about the important order would be nice too.
