### ISSUE TITLE
Delete my account from Coko Foundation's GitLab

### ISSUE THREAD

**Issue by JaimeObregon** [pagedjs/pagedjs#201]
I apologize in advance if this is too personal, but I have no other way to express it.

I have tried to contribute selflessly to this fabulous project. However, as I wrote two years ago in #93, the development and community are divided between two platforms: GitHub and GitLab. As I said at the time, this fragments the community and makes it difficult to contribute.

I once opened an account on gitlab.coko.foundation and made my contributions there. They no longer appear under my name because they were lost in an update to that private instance of GitLab.

Now, I am trying to delete my account on the foundation's private GitLab, but even this is not possible, as soon as I log in, it asks me to activate two-factor authentication (2FA) with a mobile app that I do not wish to install. I cannot escape this page; it is absolutely impossible for me even to navigate the repository once I log in. It's a dead end.

I open this issue to cordially ask the administrators to close my account "jaime.gomez" and delete my personal data at https://gitlab.coko.foundation/. Thank you very much and best wishes for this excellent project!

<img width="1416" alt="Xnapper-2024-04-20-11 04 31" src="https://github.com/pagedjs/pagedjs/assets/417226/8c718118-6116-4638-b9d2-13664328389a">

**Comment by lunarcloud** [comment]
This web page seems to no longer exist.

**Comment by JaimeObregon** [comment]
@lunarcloud The whole project seems unmaintained, but the GitLab instance [is still up](https://gitlab.coko.foundation/pagedjs/pagedjs).

I kindly request @fchasen assistance with this issue.

**Comment by julientaq** [comment]
Hey @JaimeObregon 

yes the code is divided between github and gitlab, and the conversations about what to do never really ended up with a working solution (yet?).

the contrib you made were done on the gitlab.cabbagetreelab which was removed some years ago, while the content was kept.

That said i found your account in the gitlab. i renamed all the data to “removed user”.
