### ISSUE TITLE
PDF Outline all links point to page 1

### ISSUE THREAD

**Issue by itlackey** [pagedjs/pagedjs#204]
I did not see a way to post an issue for the CLI, but am hopping someone here can help. I am using the cli version 0.4.3 to render a PDF. The file contains an outline that appears to have correctly found all header tags and nested them properly. However, all of the entries in the outline point to page 1 so clicking them returns you to the beginning of the book.

Has anyone encountered this and/or found a fix? Any help is much appreciated!

**Comment by julientaq** [comment]
hi! you’re at the right place. 
do you have a small html/css for us to test?

**Comment by itlackey** [comment]
Hey, thanks for the quick reply!

Here is an example of the PDF outline:
![image](https://github.com/pagedjs/pagedjs/assets/6414031/f3044151-4fef-4683-a6e8-0d857a33b4fb)
[dc-dreamers-guide-cli.pdf](https://github.com/pagedjs/pagedjs/files/15327582/dc-dreamers-guide-cli.pdf)

Here is a sample of html:
[book.txt](https://github.com/pagedjs/pagedjs/files/15327574/book.txt)

**Comment by itlackey** [comment]
I may have found the issue. None of my header tags have an ID attribute. The html is generated from markdown using 11ty. I may need to add some code to auto assign id's to h tags during the generation.

Does that sound like a plausible issue/fix?
