### ISSUE TITLE
Paged.js doesn't recognize 'margin' when injected into Angular component

### ISSUE THREAD

**Issue by Slaskefar** [pagedjs/pagedjs#21]
I'm trying to make a print-friendly page in my Angular application, and I'm experimenting with the paged media css module, utilizing paged.js.

Angular doesn't let you simply add <script> tags to the index.html file, so I had to do it another way. It is a bit hackish, but I managed to get something to work by adding the paged.js polyfill dynamically in the component. It seems like everything is working EXCEPT for margins.

Here is a demonstration: https://stackblitz.com/edit/angular-ivy-vhfoho

When I implement the same code in a plain and simple HTML file, it works like a charm. 
Any ideas as to why this isn't working a 100%?

**Comment by Slaskefar** [comment]
UPDATE

I don't have any explanation as to why this happens, but I found a solution. Maybe this is useful to someone else. 

I moved my @page styling from my encapsulated component to my global stylesheet. Now pagedjs recognizes my margin styles, along with everything else.

**Comment by julientaq** [comment]
Hi @Slaskefar sorry for the late answer, i was out :)

so, it seems that you’re using the polyfill and not the js module, so Pagedjs runs on the whole DOM.

I have no experience in Angular, so i’m not totally sure on what’s the best road for that. 

But having checked with people [using react](https://codesandbox.io/s/vigorous-tree-dl3mq?fontsize=14&hidenavigation=1&theme=dark), you can use the module, and then link to the css file/data.

**Comment by Slaskefar** [comment]
No problem @julientaq :)

I think I'm realizing just now that I've misunderstood the purpose of the Previewer entirely, causing a world on pain for myself. But in the end I made it work with the other approach... Now I feel like redoing it and cleaning up my "hack" 😄 
Thanks for the reply nonetheless! 👍

**Comment by julientaq** [comment]
You’re welcome!

If you could help me understand what wasn’t clear, i’ll update the documentation :D

And keep us posted on what you’re making with Pagedjs!
