### ISSUE TITLE
Waiting for rendering to finish when printing to PDF in Chromium

### ISSUE THREAD

**Issue by 3rd3** [pagedjs/pagedjs#237]
I am using headless Chromium to render PDFs using the Chrome DevTools Protocol and Selenium. Occasionally the resulting PDF has a erroneous footers such as "Page 3 of 0".

It seems that Paged.js does not finish in time and Chromium does not wait for JavaScripts to finish before rendering the page as PDF.

What is the best solution in this case besides waiting? Can I configure Paged.js to defer the kinds of events that Chromium waits for? Or can I wait with Chromium for a particular even that Paged.js fires?

I am using the latest stable versions of everything on Debian.

Thanks.

**Comment by julientaq** [comment]
hey @3rd3 

any reason to not using pagedjs-cli?  https://github.com/pagedjs/pagedjs-cli/

you can cheng the code and see if that helps if you prefer to use your own stuff.

**Comment by 3rd3** [comment]
Thanks for the link to the CLI project. This allowed me to find this gist explaining how it works:

https://gist.github.com/cderv/08a8e3815e745d04bc71ce2dae8f71b7

    page.waitForSelector(".pagedjs_pages")

This can also be done in Selenium and it works:

https://stackoverflow.com/a/59130336
