### ISSUE TITLE
Partial pagination

### ISSUE THREAD

**Issue by chybyk** [pagedjs/pagedjs#24]
Hello.
Can I specify only part of the DOM for pagination?
For examle choose some div by ID.

Thanks.

**Comment by julientaq** [comment]
hi @chybyk 

the question is a little vague, as you may have different needs. 
Could you elaborate a bit on what you’d like to do? 

The simplest answer: you can add a simple css `@media print { .xxx {display:  none; } }` to hide the elements you dont want to see in the preview.

**Comment by chybyk** [comment]
I just started studying pagedjs, but as I understand, it pagination all page (body tag). 
I need to make a control panel at the top of the page and a pagination block below.

**Comment by julientaq** [comment]
did you try to use the node module? 

```
$ npm install pagedjs
```
```
import { Previewer } from 'pagedjs';

let paged = new Previewer();

let flow = paged.preview(DOMContent, ["path/to/css/file.css"], document.body).then((flow) => {
	console.log("Rendered", flow.total, "pages.");
})
```

i’ll add a bit of documentation about that asap. I’ll also ask some user for examples, and @fchasen to answer you with more knowledge than i have :)

**Comment by chybyk** [comment]
Thank you!
I will try your example :)

**Comment by julientaq** [comment]
If you want to discuss more, you can head over to https://mattermost.pagedmedia.org :)

**Comment by chybyk** [comment]
I have made some progress, but I have not been able to figure out how to set the PagedConfig correctly. In the pagedjs javascript file PagedConfigis is always null (always auto run preview)

**Comment by chybyk** [comment]
I solved my problem, moved my script to the top :)
Thanks

**Comment by julientaq** [comment]
Awesome!
Thanks for letting us know!
