### ISSUE TITLE
Add :last pseudo selector

### ISSUE THREAD

**Issue by tvroylandt** [pagedjs/pagedjs#33]
Thanks for this awesome work !

Would it be possible to add a `:last` pseudo selector to allow us to select the last page of a document (like the `:first` in fact) ?

Thanks !

**Comment by julientaq** [comment]
Hey @tvroylandt!

the `:last` pseudo element is not part of the specs. 

We’ll add some options for that later, as it’s been requested on https://gitlab.pagedmedia.org/tools/pageds

**Comment by tvroylandt** [comment]
Thank you @julientaq ! I forgot to check Gitlab too !

I will follow the subject on it
