### ISSUE TITLE
The docs mention interface.css, which does not exist

### ISSUE THREAD

**Issue by JaimeObregon** [pagedjs/pagedjs#34]
The docs [state](https://www.pagedjs.org/documentation/02-getting-started-with-paged-js/#preview-your-work-interface):

> ## Preview your work (interface)
>
>Paged.js will manipulate the DOM so the browser can understand the css rules you wrote. On screen, pages will be shown from top to bottom on the left side of the page. To have a better understanding of what’s happening on the page, we made a small CSS file call interface that defines the layout to show your book on screen. Since we’re using @media screen, page borders and shadow won’t appear on paper when printed. To download the file of the interface go to the repo on gitlab, download the interface.css file and link it to your document in the <head>. Please check the file, as it already offers options to show facing pages, recto/verso, baseline, etc.

However there is on `interface.css` file present in the current release.

**Comment by julientaq** [comment]
Hi @JaimeObregon !
Thanks for pointing that out.

The file is not part of the release, you can get it here. https://gitlab.pagedmedia.org/tools/interface-polyfill

We’re looking at a way to implement it as part of the lib, with a couple of other features we have in mind :)

**Comment by JaimeObregon** [comment]
Thank you for your prompt response, Julia. And thank you for this project — it is super!

Slightly off-topic: yesterday I have read the whole docs and found a handful of typos. I might send a PR for the docs, but I haven't found the website's source here on Github, am I right? If so, and if you find it useful, I can open an issue here pointing out to these typos.

**Comment by JaimeObregon** [comment]
Nevermind - I have just found it [on your self-hosted GitLab instance](https://gitlab.pagedmedia.org/tools/pagedjs-website) :-) Will send a merge request there — thank you!
