### ISSUE TITLE
Low DPI leads to pixelated background image

### ISSUE THREAD

**Issue by JaapJoris** [pagedjs/pagedjs#40]
I used the CLI tool to generate a PDF of an HTML document with an SVG background. It works, but the resolution of the background image is very low. Attached you will find an example PDF.

Is there any way to increase the DPI? I've looked in the documentation but I couldn't find anything. I have specified the background image like this:

```
<style>
      .pagedjs_sheet {
          background-image: url('data:image/svg+xml;utf8,{{ insert_urlencoded_svg_here }}');
      }
</style>
```

[invoice.pdf](https://github.com/pagedjs/pagedjs/files/6122294/invoice.pdf)

**Comment by julientaq** [comment]
Hi @JaapJoris welcome around.

It’s on the list of the things i want to explore: background-image is sometimes blurry (especially with svg).

I would says that your best shot here is to add the svg to the element, and set its position as fixed. It will be repeated on all page, and the svg will be vector, so you’ll have no issues with resolution anymore.

**Comment by JaapJoris** [comment]
Thank you very much for your quick response! I have tried the following and it works perfectly:

```
<html>
  <head>
    <style>
      svg {
        position: fixed;
      }
    </style>
  </head>
  <body>
    <svg>...</svg>
    ...
  </body>
</html>
```

The background image is razor sharp now. Again, thank you for helping me out!

**Comment by julientaq** [comment]
You’re welcome!
Just to make sure, you’re not using any `background-image` property right?

**Comment by JaapJoris** [comment]
Correct, no `background-image` property anymore. I just included the SVG directly and set `position: fixed`. That is a neat trick, thank you very much!
