### ISSUE TITLE
Generated preview removes my elemenents

### ISSUE THREAD

**Issue by MateuszGrzy** [pagedjs/pagedjs#49]
I use this library to preview some HTMLs to my book and I noticed that some of my elements are moved away from page instead of cropped out of one page and put it to another.
HTML still exist in page but it is invisible and when I zoom out screen I can find it on right side of previeved output
![pagedjs-issuee](https://user-images.githubusercontent.com/20776274/121022048-49b28e00-c7a2-11eb-8489-89f5a1f60b52.png)

**Comment by MateuszGrzy** [comment]
Solved it by myself. I had layout shift because of include fonts form google and font awesome in footer and what I just do is placed it to head before pagedjs script

**Comment by julientaq** [comment]
Hi @MateuszGrzy !
Thanks for your issue.

And for your answer. 
Also this shouldn’t have stopped Paged.js from working. 
If you have some html and css to try, we can check this out :D
