### ISSUE TITLE
Table lesson generating an infinite number of pages

### ISSUE THREAD

**Issue by zopyx** [pagedjs/pagedjs#5]
This lesson 

https://github.com/zopyx/print-css-rocks/tree/master/lessons/lesson-tables

wants to generate an infinite amount of pages.

The process does not terminate.
 
The expect number of pages should be 4 or 5.

**Comment by julientaq** [comment]
Thanks for that one, it’s a good catch!

What breaks the rendering is the position of the `tfooter` element in the HTML.
Chrome tries to move it to the end of the table, which doesnt exist yet.

@fchasen we need to update the table module to handle those cases by moving the elements in the table `afterParsed`.

**Comment by julientaq** [comment]
We now have a fix for the infinite loop, but we still need to update our work on the tables :)
