### ISSUE TITLE
Is this project still being supported?

### ISSUE THREAD

**Issue by demius** [pagedjs/pagedjs#62]
First off, this project is fantastic and I'm really, *really* hoping the answer to my question is a resounding, "no!". Does the project require funding for continued development?

**Comment by julientaq** [comment]
Hi there @demius!

Thanks for the kind words. Paged.js is actively maintained. We just got out of a repos / spam attack, and we’re getting back on track, trying to have a better system for the future. This happened when we decided to rebuild the project website under 11ty, while offering support to our users who contacted us. And that just sink time like a black hole.

Anyway @fchasen our core dev has been working quite a lot on a better support for tables (which is way harder than we thought) and he’s got sidetracked with a rewriting of the CLI thanks to some obscure chromium / pupeteer updates. We’re also talking about how we can have a proper reusable plugin system for users to share codes and tools.

Our main codebase has moved to https://gitlab.coko.foundation, 
and almost all the support and conversations happens in mattermost.coko.foundation. 

In terms of funding, if you want to discuss a bit, you can get in touch on the mattermost, it will be easier than git hub issues. As an open source project, having enough money to have time to only work on paged.js is something we haven’t achieve yet :D

Thanks again for your words!

**Comment by demius** [comment]
Thanks for the feedback, Julien, much appreciated and again, absolutely fantastic project. I've tried to create an account on Gitlab, but it seems that it needs to be approved on your end? It might be worthwhile deprecating this repo and providing a link to Gitlab instead.

**Comment by julientaq** [comment]
:)

Weird. on the gitlab.coko.foundation? i’ll look into it. 

(@fchasen wants to have a clone repo here, that’s why it’s still there, but i agree, we should tell people).

**Comment by demius** [comment]
Nevermind, I was being a tool. Account created successfully!

**Comment by GustZertic** [comment]
Hi @julientaq,
Is there an ETA on the table rewrite by @fchasen? We're replacing WK with Paged and the only thing holding us back from using it in production is the fact that tables are still wonky from time to time.

**Comment by julientaq** [comment]
i’ll ask!

**Comment by probabble** [comment]
@julientaq  GitLab wants me to hand over full API access to my account in order to view the Paged project there. Is that... on purpose?
![Screen Shot 2022-03-22 at 1 06 38 PM](https://user-images.githubusercontent.com/3421159/159566692-630a268b-c42c-4882-8dd2-671bcdbdd22f.png)

**Comment by probabble** [comment]
ok, seems like it's just the links from this repo (and the first google result) that cause that permissions request. Probably a thing trying to link COKO's self-hosted gitlab against my gitlab creds. 

Anyway, this is the link that you can see anonymously: https://gitlab.coko.foundation/pagedjs/pagedjs

**Comment by MathisPct** [comment]
> Hi there @demius!
> 
> Thanks for the kind words. Paged.js is actively maintained. We just got out of a repos / spam attack, and we’re getting back on track, trying to have a better system for the future. This happened when we decided to rebuild the project website under 11ty, while offering support to our users who contacted us. And that just sink time like a black hole.
> 
> Anyway @fchasen our core dev has been working quite a lot on a better support for tables (which is way harder than we thought) and he’s got sidetracked with a rewriting of the CLI thanks to some obscure chromium / pupeteer updates. We’re also talking about how we can have a proper reusable plugin system for users to share codes and tools.
> 
> Our main codebase has moved to https://gitlab.coko.foundation, and almost all the support and conversations happens in mattermost.coko.foundation.
> 
> In terms of funding, if you want to discuss a bit, you can get in touch on the mattermost, it will be easier than git hub issues. As an open source project, having enough money to have time to only work on paged.js is something we haven’t achieve yet :D
> 
> Thanks again for your words!

Hello ! You are refactoring pagedjs-cli? :)

**Comment by julientaq** [comment]
hi there!

@fchasen is spending on time on making the cli more reliable and stable. 

I’m not sure that refactoring is the right word, but we’re definitely move lines of codes, edit some lines here and ther…
oh wait. that’s refactoring, right? :D

Do you have any thoughs on that @MathisPct?
