### ISSUE TITLE
Incorrect Handling of Neutral Characters in Bidi Text

### ISSUE THREAD

**Issue by jcuenod** [pagedjs/pagedjs#67]
Given this sample document:

```
<!DOCTYPE html>
<html>

<body>
    <p>
        Some LTR text with RTL text afterwards: תסט תסט.<sup>23</sup>
    </p>
</body>

</html>
```

I would expect the Hebrew characters to appear to the left of the period and the superscript number. However, when I run `pagedjs-cli` on it, it produces output like this:

![image](https://user-images.githubusercontent.com/4253884/162352681-f1d8c9b2-946b-400b-971a-cde12504b7a5.png)

I'm not sure if numbers are considered neutrals so perhaps the title of this issue is wrong. I also know that I could explicitly inject an LTR marker (`U+200E`) to fix it but I'm hoping there's a better fix than sprinkling these marks all over my documents.

**Comment by julientaq** [comment]
Hi there.

The behavior is the exact same in the browser. I have some reading on how LTR work to see if we can do something better but i’m afraid that it’s on the browser as we’re using its justification engine.

That  said. following this : 

https://stackoverflow.com/questions/62468519/mixing-rtl-and-ltr-text-in-html

you would want to have the element in another lang in a span (which would be quite useful in terms of accessibility imho) and use the   `unicode-bidi: isolate;`

Your mix : https://codepen.io/julientaq/pen/BaJxzzR

That would be my path, but again, bidi is something we haven’t spent too much on it.

**Comment by jcuenod** [comment]
Fair enough—closing. I noticed that FF was not handling it like I expected and assumed this might be the reason. I'm probably going to have a bunch of preprocessing scripts that run (if this workflow works for me) and I guess I can just inject LTR marks.

**Comment by julientaq** [comment]
Keep us posted, we want more RTL and internationalization example :)

**Comment by jcuenod** [comment]
I'm using this code to preprocess my HTML (my workflow is actually odt -> md -> html -> preprocess -> pagedjs)

```js
// Regex to match substrings that end with at least one Hebrew character.
// They may be preceded by * Hebrew characters and whitespace
// (I don't want to grab whitespace on its own or the trailing whitespace)
const regex = /([\u0590-\u05FF\uFB2A-\uFB4E][\u0590-\u05FF\uFB2A-\uFB4E\s])*[\u0590-\u05FF\uFB2A-\uFB4E]+/g
const ltrMark = '\u200E'

module.exports = html => {
    const htmlWithLtrMarks = html.replace(regex, match => {
        if (match.trim()) {
            return match + ltrMark
        }
        return match
    })
    // remove duplicate markers (because I've manually inserted some)
    return htmlWithLtrMarks.replace(ltrMark + ltrMark, ltrMark)
}
```
