### ISSUE TITLE
Contents of Named Page (Cover-Page) being repeated on the 2nd page

### ISSUE THREAD

**Issue by benz-law** [pagedjs/pagedjs#73]
Contents of Named Page (Cover-Page, First Page of the document) being repeated on the 2nd page and contents of 2nd page is super-imposed on it on the 2nd page.

Have saved the pdf of 2 pages rendered both by the browser (Perfect Rendition) and by pagedjs-cli (Repeat & super-imposition).

Is it a bug on the part of pagedjs-cli or puppeteer/chromium.

OS :  CentOS 7
pagedjs-cli version: 1.0.6 (latest)
chromium-browser version: 99.0.4844.84
[Sample-pagedjs-cli.pdf](https://github.com/pagedjs/pagedjs/files/8478342/Sample-pagedjs-cli.pdf)
[Sample-Browser.pdf](https://github.com/pagedjs/pagedjs/files/8478344/Sample-Browser.pdf)

**Comment by julientaq** [comment]
hi!
sorry i missed your issue
did you manage to get it right?

**Comment by benz-law** [comment]
Hello julientaq,
The issue still remains. The first page (Cover Page) is rendered correctly by pagedjs-cli but the second page had the contents of the first page and 2nd page overlapped. Am still trying to figure it out.

**Comment by benz-law** [comment]
I have tested without any css file just vanilla html, the pagedjs-cli is rendering erroneously in the second page !!!
[test-pjs.pdf](https://github.com/pagedjs/pagedjs/files/8505753/test-pjs.pdf)

<!DOCTYPE html>
<html>

<head>
    <script src="js/paged.polyfill.js"></script>
</head>

<body>

    <p style="text-align: center;">&nbsp;</p>
    <h3 style="text-align: center;"><span style="font-family: arial, helvetica, sans-serif; font-size: 16pt; color: #ba372a;">What is Lorem Ipsum?</span>
        <br />
        <span style="font-family: arial, helvetica, sans-serif; font-size: 12pt;">Printing and Typesetting</span>
    </h3>
    <p style="text-align: justify; line-height: 2;">
        <span style="font-family: helvetica, sans-serif; font-size: 12pt;">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has
            survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop
            publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem
            Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their
            default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
            </span>
    </p>

    <p style="text-align: justify; line-height: 2.5;">
        <span style="font-family: 'courier new', courier, monospace; font-size: 12pt;">
                <strong>Where does it come from?</strong>
                Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
            </span>
    </p>
    <p style="text-align: justify; line-height: 2.5;">
        <span style="font-family: 'courier new', courier, monospace; font-size: 12pt;">
                The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.
            </span>
    </p>
    <p style="text-align: justify; line-height: 2.5;"><span style="font-family: 'courier new', courier, monospace; font-size: 12pt;">
            <strong>Where can I get some?</strong>
            There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
        </span>
    </p>
    <p style="text-align: justify; line-height: 2.5; text-align: center;"><span style="font-family: 'courier new', courier, monospace; font-size: 12pt;">-o0o-</span></p>


</body>

</html>

**Comment by julientaq** [comment]
hi @benz-law 

sorry, today was a bank holiday here.

If you run paged.js cli, you need to remove the call to paged.js in the html, otherwise it will paginate twice, and you’ll get your error.

I just made it work  by removing the `<script src="roadTo/pagedjs.polyfill.js">`

**Comment by benz-law** [comment]
Hi @julientaq ,
Thank you so much... Issue Resolved !!!
